// GENERATED FILE — DO NOT EDIT
// Generated by: ael_pipeline.py
// Timestamp:    2026-05-24T08:10:00Z
//
// Source files:
//   AFID registry : /home/roosterpro/Desktop/akash/afid/yaml/com/amd/ael/afid_registry.yaml
//   Event map     : /home/roosterpro/Desktop/akash/afid/yaml/com/amd/ael/event_afid_map.yaml
//
// This header provides a zero-runtime-overhead AFID lookup table for use
// in the AEL (AMD Event Logging) enrichment layer (extensions::create()).

#pragma once

#include <string>
#include <unordered_map>

namespace amd::ael {

// Event ID -> AFID mapping (build-time generated, only valid+mapped events)
static const std::unordered_map<std::string, std::string> eventToAfid = {
    {"xyz.openbmc_project.Sensor.Threshold.ReadingAboveUpperCriticalThreshold", "AFID_0x3002"},  // Sensor reading above upper critical threshold
    {"xyz.openbmc_project.Sensor.Threshold.ReadingAboveUpperHardShutdownThreshold", "AFID_0x3004"},  // Sensor reading above upper hard shutdown threshold
    {"xyz.openbmc_project.Sensor.Threshold.ReadingAboveUpperSoftShutdownThreshold", "AFID_0x3003"},  // Sensor reading above upper soft shutdown threshold
    {"xyz.openbmc_project.Sensor.Threshold.ReadingAboveUpperWarningThreshold", "AFID_0x3001"},  // Sensor reading above upper warning threshold
    {"xyz.openbmc_project.Sensor.Threshold.ReadingBelowLowerCriticalThreshold", "AFID_0x3006"},  // Sensor reading below lower critical threshold
    {"xyz.openbmc_project.Sensor.Threshold.ReadingBelowLowerHardShutdownThreshold", "AFID_0x3008"},  // Sensor reading below lower hard shutdown threshold
    {"xyz.openbmc_project.Sensor.Threshold.ReadingBelowLowerSoftShutdownThreshold", "AFID_0x3007"},  // Sensor reading below lower soft shutdown threshold
    {"xyz.openbmc_project.Sensor.Threshold.ReadingBelowLowerWarningThreshold", "AFID_0x3005"},  // Sensor reading below lower warning threshold
    {"xyz.openbmc_project.Sensor.Threshold.ReadingCritical", "AFID_0x3009"},  // Sensor reading critical
    {"xyz.openbmc_project.Sensor.Threshold.ReadingNoLongerCritical", "AFID_0x300A"},  // Sensor reading no longer critical
    {"xyz.openbmc_project.Sensor.Threshold.SensorReadingNormalRange", "AFID_0x300B"},  // Sensor reading returned to normal range
    {"xyz.openbmc_project.State.Fan.FanFailed", "AFID_0x1001"},  // Fan hardware failure detected
    {"xyz.openbmc_project.State.Fan.FanRestored", "AFID_0x1002"},  // Fan restored to normal operation
    {"xyz.openbmc_project.State.Thermal.DeviceOperatingNormalTemperature", "AFID_0x2002"},  // Device returned to normal operating temperature
    {"xyz.openbmc_project.State.Thermal.DeviceOverOperatingTemperatureFault", "AFID_0x2001"},  // Device over operating temperature fault
};

/**
 * Look up the AFID for a given OpenBMC event ID.
 *
 * @param event  Fully-qualified event ID
 *               e.g. "xyz.openbmc_project.State.Fan.FanFailed"
 * @return       AFID string (e.g. "AFID_0x1001"), or "AFID_UNKNOWN" if not mapped
 */
inline const char* lookupAfid(const std::string& event)
{
    auto it = eventToAfid.find(event);
    if (it != eventToAfid.end()) {
        return it->second.c_str();
    }
    return "AFID_UNKNOWN";
}

} // namespace amd::ael
