// GENERATED FILE — DO NOT EDIT
// Generated by: ael_pipeline.py
// Source files:
//   AFID registry : yaml/com/amd/ael/afid_registry.yaml
//   Event map     : yaml/com/amd/ael/event_afid_map.yaml
//
// This header provides a zero-runtime-overhead AFID lookup table for use
// in the AEL (AMD Event Logging) enrichment layer (extensions::create()).
//
// Real AMD AFID Event List — integers 15-34 (© AMD 2025).

#pragma once

#include <string>
#include <unordered_map>

namespace amd::ael {

// Event ID -> AFID mapping (build-time generated, only valid+mapped events)
static const std::unordered_map<std::string, std::string> eventToAfid = {
    // Fan events
    {"xyz.openbmc_project.State.Fan.FanFailed",    "AFID_26"},  // Device Internal | HWA | Fatal
    {"xyz.openbmc_project.State.Fan.FanRestored",  "AFID_29"},  // Device Internal | All Others | Corrected

    // Thermal events
    {"xyz.openbmc_project.State.Thermal.DeviceOverOperatingTemperatureFault",  "AFID_26"},  // Device Internal | HWA | Fatal
    {"xyz.openbmc_project.State.Thermal.DeviceOperatingNormalTemperature",     "AFID_29"},  // Device Internal | All Others | Corrected

    // Sensor threshold — critical/fatal → AFID_25 (HBM All Others Fatal)
    {"xyz.openbmc_project.Sensor.Threshold.ReadingAboveUpperCriticalThreshold",    "AFID_25"},
    {"xyz.openbmc_project.Sensor.Threshold.ReadingAboveUpperHardShutdownThreshold","AFID_25"},
    {"xyz.openbmc_project.Sensor.Threshold.ReadingAboveUpperSoftShutdownThreshold","AFID_25"},
    {"xyz.openbmc_project.Sensor.Threshold.ReadingBelowLowerCriticalThreshold",    "AFID_25"},
    {"xyz.openbmc_project.Sensor.Threshold.ReadingBelowLowerHardShutdownThreshold","AFID_25"},
    {"xyz.openbmc_project.Sensor.Threshold.ReadingBelowLowerSoftShutdownThreshold","AFID_25"},
    {"xyz.openbmc_project.Sensor.Threshold.ReadingCritical",                       "AFID_25"},

    // Sensor threshold — warning/recovery → AFID_24 (HBM All Corrected)
    {"xyz.openbmc_project.Sensor.Threshold.ReadingAboveUpperWarningThreshold",  "AFID_24"},
    {"xyz.openbmc_project.Sensor.Threshold.ReadingBelowLowerWarningThreshold",  "AFID_24"},
    {"xyz.openbmc_project.Sensor.Threshold.ReadingNoLongerCritical",            "AFID_24"},
    {"xyz.openbmc_project.Sensor.Threshold.SensorReadingNormalRange",           "AFID_24"},

    // CPER — default AFID_34 (Unidentified) until decoded by amd-bmc-ras
    {"com.amd.Event.Cper.CperReported",  "AFID_34"},
};

/**
 * Look up the AFID for a given OpenBMC event ID.
 *
 * @param event  Fully-qualified event ID
 *               e.g. "xyz.openbmc_project.State.Fan.FanFailed"
 * @return       AFID string (e.g. "AFID_26"), or "AFID_UNKNOWN" if not mapped.
 */
inline const char* lookupAfid(const std::string& event)
{
    auto it = eventToAfid.find(event);
    if (it != eventToAfid.end())
    {
        return it->second.c_str();
    }
    return "AFID_UNKNOWN";
}

} // namespace amd::ael
