// SPDX-License-Identifier: Apache-2.0
// extensions/ael/ael.cpp
//
// AEL (AMD Event Logging) extension for phosphor-log-manager.

#include "ael.hpp"
#include "event_afid_map.hpp"    // generated by ael_pipeline.py at build time
#include "log_manager.hpp"
#include "extensions.hpp"

// Generated sdbusplus server bindings from
// yaml/xyz/openbmc_project/Logging/Entry/Oem.interface.yaml
#include <xyz/openbmc_project/Logging/Entry/Oem/server.hpp>

#include <phosphor-logging/lg2.hpp>
#include <sdbusplus/bus.hpp>
#include <sdbusplus/server/object.hpp>

#include <format>
#include <map>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

namespace amd::ael
{

using namespace phosphor::logging;

// ─────────────────────────────────────────────────────────────────────────────
// Type alias for the sdbusplus server object
// Generated from xyz.openbmc_project.Logging.Entry.Oem interface
// ─────────────────────────────────────────────────────────────────────────────

using OemEntryIface = sdbusplus::server::object_t<
    sdbusplus::xyz::openbmc_project::Logging::Entry::server::Oem>;

// ─────────────────────────────────────────────────────────────────────────────
// In-memory store: entry ID → OEM interface object
// ─────────────────────────────────────────────────────────────────────────────

static std::unordered_map<uint32_t, std::unique_ptr<OemEntryIface>> oemObjects;

// ─────────────────────────────────────────────────────────────────────────────
// Helpers (also exposed for unit testing via ael.hpp)
// ─────────────────────────────────────────────────────────────────────────────

std::string extractAdditionalDataValue(
    const phosphor::logging::AdditionalDataArg& additionalData,
    const std::string& key)
{
    auto it = additionalData.find(key);
    if (it != additionalData.end())
    {
        return it->second;
    }
    return {};
}

std::map<std::string, std::string> buildOemData(
    const std::string& message,
    const phosphor::logging::AdditionalDataArg& additionalData)
{
    std::map<std::string, std::string> oem;

    // Always include the event ID as context for consumers
    oem["EventMessage"] = message;

    // Well-known AEL keys that producers set in their lg2::commit() call.
    // Stored with clean camelCase names for Redfish / bmcweb consumers.
    static const std::vector<std::pair<std::string, std::string>> knownKeys = {
        {"SLOT_ID",           "SlotId"},
        {"EVENT_TYPE",        "EventType"},
        {"CORRELATION_ID",    "CorrelationId"},
        {"COMPONENT_ID",      "ComponentId"},
        {"CPER_SECTION_TYPE", "CperSectionType"},
        {"GPU_ID",            "GpuId"},
        {"SEVERITY_HINT",     "SeverityHint"},
    };

    for (const auto& [rawKey, oemKey] : knownKeys)
    {
        auto val = extractAdditionalDataValue(additionalData, rawKey);
        if (!val.empty())
        {
            oem[oemKey] = std::move(val);
        }
    }

    return oem;
}

// ─────────────────────────────────────────────────────────────────────────────
// create() — main AEL enrichment hook
// ─────────────────────────────────────────────────────────────────────────────

void create(const std::string& message, uint32_t id, uint64_t timestamp,
            phosphor::logging::Entry::Level /*severity*/,
            const phosphor::logging::AdditionalDataArg& additionalData,
            const phosphor::logging::AssociationEndpointsArg& /*associations*/,
            const phosphor::logging::FFDCArg& /*ffdc*/)
{
    // ── Step 1: AFID lookup ───────────────────────────────────────────────
    const std::string serviceCode = amd::ael::lookupAfid(message);

    lg2::debug(
        "AEL: creating OEM entry for id={ID} event={MSG} serviceCode={SC} time={TS}",
        "ID", id, "MSG", message, "SC", serviceCode, "TS", timestamp);

    // ── Step 2: Build OemAdditionalData ──────────────────────────────────
    auto oemData = buildOemData(message, additionalData);

    // ── Step 3: Attach xyz.openbmc_project.Logging.Entry.Oem ─────────────
    try
    {
        // Acquire bus handle
        auto bus = sdbusplus::bus::new_default();
        auto objPath = std::format("/xyz/openbmc_project/logging/entry/{}", id);

        auto oemObj = std::make_unique<OemEntryIface>(bus, objPath.c_str());

        // Set properties defined in the interface
        oemObj->serviceCode(serviceCode);
        oemObj->oemAdditionalData(oemData);

        // Store it so it stays on the bus
        oemObjects[id] = std::move(oemObj);
    }
    catch (const std::exception& e)
    {
        lg2::error("AEL: failed to attach OEM interface for log {ID}: {ERR}",
                   "ID", id, "ERR", e);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// erase() — cleanup hook
// ─────────────────────────────────────────────────────────────────────────────

void erase(uint32_t id)
{
    auto it = oemObjects.find(id);
    if (it != oemObjects.end())
    {
        lg2::debug("AEL: removing Entry.Oem for entry {ID}", "ID", id);
        oemObjects.erase(it);
    }
}

REGISTER_EXTENSION_FUNCTION(create);
REGISTER_EXTENSION_FUNCTION(erase);

} // namespace amd::ael