// SPDX-License-Identifier: Apache-2.0
// extensions/ael/ael.cpp
//
// AEL (AMD Event Logging) extension for phosphor-log-manager.
//
// How it hooks in (same as IBM PEL):
//
//   phosphor-log-manager main loop
//     └── entry created
//           └── extensions::create() iterates all registered extensions
//                 └── amd::ael::create()   ← THIS FILE
//                       ├── lookupAfid()   ← event_afid_map.hpp (build-time generated)
//                       ├── buildOemData() ← extract from additionalData
//                       └── attach xyz.openbmc_project.Logging.Entry.Oem
//                             ├── ServiceCode       = AFID
//                             └── OemAdditionalData = {SlotId, EventType, ...}
//
// REGISTER_EXTENSION_FUNCTION at the bottom wires create() and erase()
// into phosphor-log-manager's extension callback list at startup.

#include "ael.hpp"
#include "event_afid_map.hpp"    // generated by ael_pipeline.py at build time
#include "extensions/extensions.hpp"

// Generated sdbusplus server bindings from
// yaml/xyz/openbmc_project/Logging/Entry/Oem.interface.yaml
#include <xyz/openbmc_project/Logging/Entry/Oem/server.hpp>

#include <phosphor-logging/lg2.hpp>
#include <sdbusplus/bus.hpp>
#include <sdbusplus/server/object.hpp>

#include <format>
#include <map>
#include <memory>
#include <string>
#include <unordered_map>
#include <vector>

namespace amd::ael
{

// ─────────────────────────────────────────────────────────────────────────────
// Type alias for the sdbusplus server object
// Generated from xyz.openbmc_project.Logging.Entry.Oem interface
// ─────────────────────────────────────────────────────────────────────────────

using OemEntryIface = sdbusplus::server::object_t<
    sdbusplus::xyz::openbmc_project::Logging::Entry::server::Oem>;

// ─────────────────────────────────────────────────────────────────────────────
// In-memory store: entry ID → OEM interface object
//
// Keeps the sdbusplus object alive as long as the log entry exists.
// When erase() is called, we remove the unique_ptr — the destructor
// removes the D-Bus interface from the bus automatically.
// ─────────────────────────────────────────────────────────────────────────────

static std::unordered_map<uint32_t, std::unique_ptr<OemEntryIface>> oemObjects;

// ─────────────────────────────────────────────────────────────────────────────
// Helpers (also exposed for unit testing via ael.hpp)
// ─────────────────────────────────────────────────────────────────────────────

std::string extractAdditionalDataValue(
    const phosphor::logging::AdditionalDataArg& additionalData,
    const std::string& key)
{
    const std::string prefix = key + "=";
    for (const auto& item : additionalData)
    {
        if (item.starts_with(prefix))
        {
            return item.substr(prefix.size());
        }
    }
    return {};
}

std::map<std::string, std::string> buildOemData(
    const std::string& message,
    const phosphor::logging::AdditionalDataArg& additionalData)
{
    std::map<std::string, std::string> oem;

    // Always include the event ID as context for consumers
    oem["EventMessage"] = message;

    // Well-known AEL keys that producers set in their lg2::commit() call.
    // Stored with clean camelCase names for Redfish / bmcweb consumers.
    static const std::vector<std::pair<std::string, std::string>> knownKeys = {
        {"SLOT_ID",           "SlotId"},
        {"EVENT_TYPE",        "EventType"},
        {"CORRELATION_ID",    "CorrelationId"},
        {"COMPONENT_ID",      "ComponentId"},
        {"CPER_SECTION_TYPE", "CperSectionType"},
        {"GPU_ID",            "GpuId"},
        {"SEVERITY_HINT",     "SeverityHint"},
    };

    for (const auto& [rawKey, oemKey] : knownKeys)
    {
        auto val = extractAdditionalDataValue(additionalData, rawKey);
        if (!val.empty())
        {
            oem[oemKey] = std::move(val);
        }
    }

    return oem;
}

// ─────────────────────────────────────────────────────────────────────────────
// create() — main AEL enrichment hook
// ─────────────────────────────────────────────────────────────────────────────

void create(const std::string& message,
            phosphor::logging::Entry::Level /*severity*/,
            const phosphor::logging::AssociationList& /*associations*/,
            const phosphor::logging::AdditionalDataArg& additionalData,
            const phosphor::logging::FFDCArg& /*ffdc*/,
            uint32_t id,
            phosphor::logging::internal::Manager& /*manager*/)
{
    // ── Step 1: AFID lookup ───────────────────────────────────────────────
    // lookupAfid() is a hash map lookup on a static const unordered_map.
    // Zero I/O, zero parsing, zero allocation.
    // Returns "AFID_UNKNOWN" if the event is not in the map.
    const std::string serviceCode = amd::ael::lookupAfid(message);

    lg2::debug(
        "AEL: creating OEM entry for id={ID} event={MSG} serviceCode={SC}",
        "ID", id, "MSG", message, "SC", serviceCode);

    // ── Step 2: Build OemAdditionalData ──────────────────────────────────
    auto oemData = buildOemData(message, additionalData);

    // ── Step 3: Attach xyz.openbmc_project.Logging.Entry.Oem ─────────────
    //
    // We attach the OEM interface to the SAME object path as the base entry.
    // bmcweb reads both interfaces from one introspect call — no extra hops.
    //
    //   /xyz/openbmc_project/logging/entry/<id>
    //     ├── xyz.openbmc_project.Logging.Entry       (phosphor-logging)
    //     └── xyz.openbmc_project.Logging.Entry.Oem  (AEL — attached here)

    const auto entryPath =
        std::format("/xyz/openbmc_project/logging/entry/{}", id);

    try
    {
        auto& bus = sdbusplus::bus::new_default();

        // Construct the interface object. sdbusplus registers it on D-Bus
        // immediately. Properties are set below before any signals fire.
        auto obj = std::make_unique<OemEntryIface>(bus, entryPath.c_str());

        obj->serviceCode(serviceCode);
        obj->oemAdditionalData(oemData);

        // Store so the object stays alive as long as the log entry exists
        oemObjects[id] = std::move(obj);

        lg2::info(
            "AEL: attached Entry.Oem to entry {ID} "
            "serviceCode={SC} oemKeys={N}",
            "ID", id,
            "SC", serviceCode,
            "N",  static_cast<uint32_t>(oemData.size()));
    }
    catch (const std::exception& e)
    {
        lg2::error(
            "AEL: failed to attach Entry.Oem for entry {ID}: {ERR}",
            "ID", id, "ERR", e.what());
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// erase() — cleanup hook
// ─────────────────────────────────────────────────────────────────────────────

void erase(uint32_t id)
{
    auto it = oemObjects.find(id);
    if (it != oemObjects.end())
    {
        lg2::debug("AEL: removing Entry.Oem for entry {ID}", "ID", id);
        oemObjects.erase(it);
        // unique_ptr destructor → sdbusplus removes interface from D-Bus
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Extension registration
// Mirrors IBM PEL's REGISTER_EXTENSION_FUNCTION calls exactly.
// These macros add function pointers to the global extension list that
// phosphor-log-manager iterates on every log entry lifecycle event.
// ─────────────────────────────────────────────────────────────────────────────

REGISTER_EXTENSION_FUNCTION(create);
REGISTER_EXTENSION_FUNCTION(erase);

} // namespace amd::ael