// extensions/ael/ael_entry.cpp

#include "ael_entry.hpp"
#include "event_afid_map.hpp"    // build-time generated by ael_pipeline.py

#include <phosphor-logging/lg2.hpp>

#include <format>
#include <vector>

namespace amd::ael
{


static const std::vector<std::pair<std::string, std::string>> knownKeyMap = {
    {"SLOT_ID",           "AEL.SLOT_ID"},
    {"EVENT_TYPE",        "AEL.EVENT_TYPE"},
    {"CORRELATION_ID",    "AEL.CORRELATION_ID"},
    {"COMPONENT_ID",      "AEL.COMPONENT_ID"},
    {"CPER_SECTION_TYPE", "AEL.SUBTYPE"},
    {"GPU_ID",            "AEL.GPU_ID"},
    {"SEVERITY_HINT",     "AEL.SEVERITY_OVERRIDE"},
};


std::string AelEntry::extractValue(
    const phosphor::logging::AdditionalDataArg& additionalData,
    const std::string& key)
{
    auto it = additionalData.find(key);
    if (it != additionalData.end())
    {
        return it->second;
    }
    return {};
}

std::map<std::string, std::string> AelEntry::buildOemData(
    const std::string& message,
    const phosphor::logging::AdditionalDataArg& additionalData)
{
    std::map<std::string, std::string> oem;

    oem["AEL.VERSION"] = "1.0";
    oem["AEL.TYPE"] = "SIMPLE"; // Default to SIMPLE for now

    if (message.find("CperReported") != std::string::npos)
    {
        oem["AEL.TYPE"] = "COMPLEX";
        oem["AEL.SUBTYPE"] = "CPER";
        
        auto path = extractValue(additionalData, "Path");
        if (!path.empty())
        {
            oem["AEL.DATA.URI"] = "file://" + path;
        }
    }

    // Add mapped keys
    for (const auto& [rawKey, oemKey] : knownKeyMap)
    {
        auto val = extractValue(additionalData, rawKey);
        if (!val.empty())
        {
            oem[oemKey] = std::move(val);
        }
    }

    return oem;
}

 // ──────────────────────────────────────────────────────────────────────────

AelEntry::AelEntry(sdbusplus::bus_t& bus, uint32_t id,
                   const std::string& message,
                   [[maybe_unused]] phosphor::logging::Entry::Level severity,
                   const phosphor::logging::AdditionalDataArg& additionalData,
                   const std::string& serviceCode) :
    _id(id),
    _serviceCode(serviceCode),
    _oemData(buildOemData(message, additionalData))
{
   
    const auto path =
        std::format("/xyz/openbmc_project/logging/entry/{}", id);

    try
    {
        _iface = std::make_unique<OemEntryIface>(bus, path.c_str());
        _iface->serviceCode(_serviceCode);
        _iface->oemAdditionalData(_oemData);

        lg2::info(
            "AEL: entry {ID} OEM attached — serviceCode={SC} keys={N}",
            "ID", id,
            "SC", _serviceCode,
            "N",  static_cast<uint32_t>(_oemData.size()));
    }
    catch (const std::exception& e)
    {
        lg2::error(
            "AEL: failed to attach Entry.Oem for entry {ID}: {ERR}",
            "ID", id, "ERR", e.what());
    }
}

} // namespace amd::ael