// extensions/ael/ael_entry.cpp

#include "ael_entry.hpp"
#include "event_afid_map.hpp"    // build-time generated by ael_pipeline.py

#include <phosphor-logging/lg2.hpp>

#include <format>
#include <vector>

namespace amd::ael
{

// ─────────────────────────────────────────────────────────────────────────────
// Known AdditionalData key → OemAdditionalData camelCase key mapping
// ─────────────────────────────────────────────────────────────────────────────

static const std::vector<std::pair<std::string, std::string>> knownKeyMap = {
    {"SLOT_ID",           "SlotId"},
    {"EVENT_TYPE",        "EventType"},
    {"CORRELATION_ID",    "CorrelationId"},
    {"COMPONENT_ID",      "ComponentId"},
    {"CPER_SECTION_TYPE", "CperSectionType"},
    {"GPU_ID",            "GpuId"},
    {"SEVERITY_HINT",     "SeverityHint"},
};

// ─────────────────────────────────────────────────────────────────────────────
// Static helpers
// ─────────────────────────────────────────────────────────────────────────────

std::string AelEntry::extractValue(
    const phosphor::logging::AdditionalDataArg& additionalData,
    const std::string& key)
{
    auto it = additionalData.find(key);
    if (it != additionalData.end())
    {
        return it->second;
    }
    return {};
}

std::map<std::string, std::string> AelEntry::buildOemData(
    const std::string& message,
    const phosphor::logging::AdditionalDataArg& additionalData)
{
    std::map<std::string, std::string> oem;
    oem["EventMessage"] = message;

    for (const auto& [rawKey, oemKey] : knownKeyMap)
    {
        auto val = extractValue(additionalData, rawKey);
        if (!val.empty())
        {
            oem[oemKey] = std::move(val);
        }
    }

    return oem;
}

// ─────────────────────────────────────────────────────────────────────────────
// Constructor — this is where the OEM interface gets attached to D-Bus
// ─────────────────────────────────────────────────────────────────────────────

AelEntry::AelEntry(uint32_t id,
                   const std::string& message,
                   const phosphor::logging::AdditionalDataArg& additionalData,
                   sdbusplus::bus_t& bus) :
    _id(id),
    _serviceCode(amd::ael::lookupAfid(message)),
    _oemData(buildOemData(message, additionalData))
{
    // Attach xyz.openbmc_project.Logging.Entry.Oem to the existing log entry
    // object path. Same path as the standard Entry — no duplication.
    //
    //   /xyz/openbmc_project/logging/entry/<id>
    //     ├── xyz.openbmc_project.Logging.Entry       (phosphor-logging)
    //     └── xyz.openbmc_project.Logging.Entry.Oem  (AEL — attached here)

    const auto path =
        std::format("/xyz/openbmc_project/logging/entry/{}", id);

    try
    {
        _iface = std::make_unique<OemEntryIface>(bus, path.c_str());
        _iface->serviceCode(_serviceCode);
        _iface->oemAdditionalData(_oemData);

        lg2::info(
            "AEL: entry {ID} OEM attached — serviceCode={SC} keys={N}",
            "ID", id,
            "SC", _serviceCode,
            "N",  static_cast<uint32_t>(_oemData.size()));
    }
    catch (const std::exception& e)
    {
        lg2::error(
            "AEL: failed to attach Entry.Oem for entry {ID}: {ERR}",
            "ID", id, "ERR", e.what());
    }
}

} // namespace amd::ael